### ISSUE TITLE
Install fonts

### ISSUE THREAD

**Issue by stefan-moraru** [milld/iasiajuta#4]
https://fonts.google.com/specimen/Montserrat

- Light
- Regular
- Bold

**Comment by emyl1an** [comment]
Resolved with PR [Setup Montserrat font](https://github.com/milld/iasiajuta/pull/8)

**Comment by emyl1an** [comment]
Resolved with PR [Setup Montserrat font](https://github.com/milld/iasiajuta/pull/8)
